FROM maven:3.6.3-openjdk-11 AS build
WORKDIR /app
COPY pom.xml /app
COPY src/main/resources/application.properties /app
COPY src/main/resources/application-integrationtest.properties /app
COPY src /app/src
RUN mvn package

FROM openjdk:11-jre-slim
WORKDIR /app
COPY --from=build /app/target/accenture-techhub-0.0.1-SNAPSHOT.war /app
EXPOSE 8080
CMD ["java", "-jar", "accenture-techhub-0.0.1-SNAPSHOT.war"]